name: Deploy PHP-FPM e NGINX
on:
  push:
    branches:
      - main  # roda o deploy automático quando fizer push na branch "main"

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Conectar via SSH e fazer o deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/teste-sci
            git pull origin main
            docker compose down
            docker compose up -d --build

